In [21]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'd:\python38\python.exe -m pip install --upgrade pip' command.


In [22]:
!python -m pip install numpy

You should consider upgrading via the 'D:\python38\python.exe -m pip install --upgrade pip' command.


In [82]:
import numpy as np

In [83]:
lst=[1,2,3,4,5,6,7]

In [84]:
type(lst)

list

In [85]:
arr=np.array(lst)

In [86]:
type(arr)

numpy.ndarray

In [87]:
arr.shape

(7,)

In [88]:
lst1=[1,2,3]
lst2=[4,5,6]
lst3=[7,8,9]

In [89]:
arr1=np.array([lst1,lst2,lst3])

In [90]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
arr1.shape

(3, 3)

In [92]:
arr1.ndim

2

In [93]:
# arr[1]=5

In [94]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [95]:
arr[:-2]

array([1, 2, 3, 4, 5])

In [98]:
arr[::-3]

array([7, 4, 1])

In [99]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [110]:
arr1[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [ ]:
arr1[0:1+1,0:1+1]

In [106]:
arr1[:,2]

array([3, 6, 9])

In [107]:
# array(row,column)

In [115]:
arr3=np.arange(0,100)

In [116]:
arr4=np.arange(0,100)

In [117]:
arr3.reshape(20,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [118]:
arr4.reshape(20,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [119]:
arr3*arr4

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
       4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776,
       5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569,
       7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604,
       9801])

In [120]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [121]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [129]:
np.random.randint(10,50,4).reshape(2,2)

array([[20, 30],
       [21, 25]])

In [134]:
np.random.randn(5,6)

array([[ 0.68935077,  0.47451338, -0.6513247 ,  0.04556048, -1.5412814 ,
        -0.57108112],
       [-0.24030332,  1.04263427, -1.77833924, -0.62124529,  0.72380586,
         0.74285581],
       [-0.10926309, -1.0923229 , -0.09845228, -0.72436132,  0.10225627,
         1.04056962],
       [-0.91887063,  0.44873366,  0.24476628, -0.1676833 , -1.20818552,
         1.98065   ],
       [-0.54757874, -1.22947174,  1.23621163,  0.61620762,  0.47282889,
        -0.31063321]])

In [136]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [138]:
arr[2]=32

In [140]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [145]:
arr1.sum(axis=0)

array([12, 15, 18])

In [146]:
arr.argmin()

0