In [20]:
!python -m pip install pandas

You should consider upgrading via the 'D:\python38\python.exe -m pip install --upgrade pip' command.


In [21]:
import pandas as pd
import numpy as np

In [24]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
df=pd.DataFrame(data=np.arange(0,25).reshape(5,5), index=["Row1", "Row2","Row3","Row4","Row5"],
                columns=["Column1", "Column2","Column3","Column4","Column5"])

In [42]:
df.head(2)

Column1  Column2  Column3  Column4  Column5
Row1        0        1        2        3        4
Row2        5        6        7        8        9

In [40]:
type(df)

pandas.core.frame.DataFrame

In [44]:
df.tail(2)

Column1  Column2  Column3  Column4  Column5
Row4       15       16       17       18       19
Row5       20       21       22       23       24

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int32
 1   Column2  5 non-null      int32
 2   Column3  5 non-null      int32
 3   Column4  5 non-null      int32
 4   Column5  5 non-null      int32
dtypes: int32(5)
memory usage: 140.0+ bytes


In [46]:
df.describe()

Column1    Column2    Column3    Column4    Column5
count   5.000000   5.000000   5.000000   5.000000   5.000000
mean   10.000000  11.000000  12.000000  13.000000  14.000000
std     7.905694   7.905694   7.905694   7.905694   7.905694
min     0.000000   1.000000   2.000000   3.000000   4.000000
25%     5.000000   6.000000   7.000000   8.000000   9.000000
50%    10.000000  11.000000  12.000000  13.000000  14.000000
75%    15.000000  16.000000  17.000000  18.000000  19.000000
max    20.000000  21.000000  22.000000  23.000000  24.000000

In [48]:
df.head()

Column1  Column2  Column3  Column4  Column5
Row1        0        1        2        3        4
Row2        5        6        7        8        9
Row3       10       11       12       13       14
Row4       15       16       17       18       19
Row5       20       21       22       23       24

In [49]:
df['Column1']

Row1     0
Row2     5
Row3    10
Row4    15
Row5    20
Name: Column1, dtype: int32

In [53]:
type(df['Column1'])

pandas.core.series.Series

In [52]:
type(df[['Column1','Column2']])

pandas.core.frame.DataFrame

In [58]:
df.loc[["Row1","Row5"]]

Column1  Column2  Column3  Column4  Column5
Row1        0        1        2        3        4
Row5       20       21       22       23       24

In [59]:
df.iloc[0:2,0:2]

Column1  Column2
Row1        0        1
Row2        5        6

In [60]:
df.head()

Column1  Column2  Column3  Column4  Column5
Row1        0        1        2        3        4
Row2        5        6        7        8        9
Row3       10       11       12       13       14
Row4       15       16       17       18       19
Row5       20       21       22       23       24

In [63]:
df.iloc[1:,1:].values

array([[ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [65]:
df.isnull()

Column1  Column2  Column3  Column4  Column5
Row1    False    False    False    False    False
Row2    False    False    False    False    False
Row3    False    False    False    False    False
Row4    False    False    False    False    False
Row5    False    False    False    False    False

In [74]:
df1=pd.DataFrame(data=[[ 0,  1,  np.nan,  3,  4],
       [ 5,  6,  np.nan , 8,  9],
       [15, 11, 12, 13, 14],
       [15, 16, np.nan, 18, 19],
       [np.nan, 21, 22, 23, 24]], index=["Row1", "Row2","Row3","Row4","Row5"],
                columns=["Column1", "Column2","Column3","Column4","Column5"])

In [75]:
df1.head()

Column1  Column2  Column3  Column4  Column5
Row1      0.0        1      NaN        3        4
Row2      5.0        6      NaN        8        9
Row3     15.0       11     12.0       13       14
Row4     15.0       16      NaN       18       19
Row5      NaN       21     22.0       23       24

In [76]:
df1.isnull().sum()

Column1    1
Column2    0
Column3    3
Column4    0
Column5    0
dtype: int64

In [77]:
df1['Column1'].value_counts()

15.0    2
0.0     1
5.0     1
Name: Column1, dtype: int64

In [78]:
df1['Column1'].unique()

array([ 0.,  5., 15., nan])

In [80]:
df1[df1['Column1']>1]

Column1  Column2  Column3  Column4  Column5
Row2      5.0        6      NaN        8        9
Row3     15.0       11     12.0       13       14
Row4     15.0       16      NaN       18       19